// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmRlB1vdUIzjru95b32aX_dfKYdw8SSuI',
    appId: '1:9641769693:web:dc67cdb5161682b4343934',
    messagingSenderId: '9641769693',
    projectId: 'mytaskmanager-75110',
    authDomain: 'mytaskmanager-75110.firebaseapp.com',
    storageBucket: 'mytaskmanager-75110.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvLI4I_NETxPhqWhDhdjYZEpu7R635gHo',
    appId: '1:9641769693:android:f70057d0cb7ea5fb343934',
    messagingSenderId: '9641769693',
    projectId: 'mytaskmanager-75110',
    storageBucket: 'mytaskmanager-75110.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXwPkkYYtMpE6eInzdzEWW-J1rHtazPbE',
    appId: '1:9641769693:ios:a0070f859f9e3794343934',
    messagingSenderId: '9641769693',
    projectId: 'mytaskmanager-75110',
    storageBucket: 'mytaskmanager-75110.firebasestorage.app',
    iosBundleId: 'com.example.mytaskmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXwPkkYYtMpE6eInzdzEWW-J1rHtazPbE',
    appId: '1:9641769693:ios:a0070f859f9e3794343934',
    messagingSenderId: '9641769693',
    projectId: 'mytaskmanager-75110',
    storageBucket: 'mytaskmanager-75110.firebasestorage.app',
    iosBundleId: 'com.example.mytaskmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmRlB1vdUIzjru95b32aX_dfKYdw8SSuI',
    appId: '1:9641769693:web:bbda24c93d3934e6343934',
    messagingSenderId: '9641769693',
    projectId: 'mytaskmanager-75110',
    authDomain: 'mytaskmanager-75110.firebaseapp.com',
    storageBucket: 'mytaskmanager-75110.firebasestorage.app',
  );
}
